{% set version = "5.0" %}

package:
  name: galois
  version: {{ version }}

source:
  url: https://github.com/IntelligentSoftwareSystems/Galois/archive/master.zip

build:
  number: 1
  skip: true # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - boost-cpp

about:
  home: iss.ices.utexas.edu/?p=projects/galois
  license: BSD
  license_file: LICENSE.txt
  summary: Library for building parallel graph algorithms.

extra:
  recipe-maintainers:
    - insertinterestingnamehere
